# Generated by Django 3.1.4 on 2021-01-07 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('documenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_author',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='document_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post_author',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='post_author',
            name='first_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='post_author',
            name='last_name',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='post_author',
            name='slug',
            field=models.SlugField(default=None, max_length=250, unique_for_date='created'),
        ),
        migrations.AddField(
            model_name='post_author',
            name='tag',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='post_author',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='post_author',
            name='title',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
