# Generated by Django 3.1.4 on 2021-01-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenter', '0002_auto_20210107_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='post_author',
            name='last_name',
        ),
    ]
