# Generated by Django 3.1.4 on 2021-04-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documenter', '0004_auto_20210107_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searcher',
            name='author',
        ),
    ]
