# Generated by Django 3.1.4 on 2021-04-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenter', '0006_searcher_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searcher',
            name='solution_image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
